export enum APP_REDUCER_ACTION_TYPE {
    SET_CONTEXT_STATE,
    CHANGE_SELECTED_RESOURCE,
    CHANGE_SELECTED_PROPERTY,
    SET_LOADED_RESOURCE,
    SET_MAX_PEOPLE_RESOURCE,
    SET_MAX_STARSHIPS_RESOURCE,
}
